export const MAIN_NAVIGATOR = 'MAIN_NAVIGATOR';
export const APP_NAVIGATOR = 'APP_NAVIGATOR';
export const VERIFICATION_NAVIGATOR = 'VERIFICATION_NAVIGATOR';

export const LOGIN_PAGE = 'LOGIN_PAGE';
export const LOGIN_PHONE_PAGE = 'LOGIN_PHONE_PAGE';

export const REGISTER_PAGE = 'REGISTER_PAGE';

export const FORGET_PASSWORD_PAGE = 'FORGET_PASSWORD_PAGE';
export const RESET_PASSWORD_PAGE = 'RESET_PASSWORD_PAGE';

export const PHONE_VERIFICATION_PAGE = 'PHONE_VERIFICATION_PAGE';
export const VERIFICATION_CODE_PAGE = 'VERIFICATION_CODE_PAGE';
export const VERIFICATION_USER_PAGE = 'VERIFICATION_USER_PAGE';

export const HOME_PAGE = 'HOME_PAGE';
export const PROFILE_PAGE = 'PROFILE_PAGE';

export const CHANGE_PHONE_PAGE = 'CHANGE_PHONE_PAGE';
export const CHANGE_PASSWORD_PAGE = 'CHANGE_PASSWORD_PAGE';

export const IMAGE_BROWSER_PAGE = 'IMAGE_BROWSER_PAGE';
export const VIEW_IMAGE_PAGE = 'VIEW_IMAGE_PAGE';

export const CANHAN_PAGE = 'CANHAN_PAGE';

export const HOTRO_PAGE = 'HOTRO_PAGE';
export const THONGTIN_PAGE = 'THONGTIN_PAGE';
export const GIOITHIEU_PAGE = 'GIOITHIEU_PAGE';

export const BACSI_DETAIL = 'BACSI_DETAIL';

export const TINTUC_DETAIL = 'TINTUC_DETAIL';

export const HUONGDAN_DETAIL = 'HUONGDAN_DETAIL';

export const DANGKY_DICHVU_PAGE = 'DANGKY_DICHVU_PAGE';
export const DANHMUC_DICHVU_PAGE = 'DANHMUC_DICHVU_PAGE';
export const LIST_DICH_VU_PAGE = 'LIST_DICH_VU_PAGE';

export const LICHSU_DICHVU_PAGE = 'LICHSU_DICHVU_PAGE';
export const LICHSU_DICHVU_DETAIL = 'LICHSU_DICHVU_DETAIL';

export const DANHGIA_PAGE = 'DANHGIA_PAGE';

export const LICHHEN_DETAIL = 'LICHHEN_DETAIL';

export const LICHSUKHAM_PAGE = 'LICHSUKHAM_PAGE';
export const LICHSUKHAM_DETAIL = 'LICHSUKHAM_DETAIL';

export const DONTHUOC_PAGE = 'DONTHUOC_PAGE';

export const KETQUAKHAM_PAGE = 'KETQUAKHAM_PAGE';

export const THONGBAO_PAGE = 'THONGBAO_PAGE';

export const THONGBAO_CANHAN = 'THONGBAO_CANHAN';

export const THONGBAO_CONGDONG = 'THONGBAO_CONGDONG';

export const HOSOSUCKHOE_PAGE = 'HOSOSUCKHOE_PAGE';

export const PHIEUKHAMSUCKHOE = 'PHIEUKHAMSUCKHOE';

export const UPLOAD_PAGE = 'UPLOAD_PAGE'

export const VIDEO_PAGE = 'VIDEO_PAGE'

export const AUDIO_PAGE = 'AUDIO_PAGE'

export const PULSEOXIMETER_PAGE = 'PULSEOXIMETER_PAGE'

export const HISTORY_PAGE = 'HISTORY_PAGE'
export const DETAIL_VIEW_PAGE = 'DETAIL_VIEW_PAGE'
export const HISTORY_ANALYSIS_PAGE = 'HISTORY_ANALYSIS_PAGE'
export const DETAIL_ANALYSIS_PAGE = 'DETAIL_ANALYSIS_PAGE'

export const SETTINGS_PAGE = 'SETTINGS_PAGE'

export const EKO_PAGE = 'EKO_PAGE'

export const DETAIL_OXIMETER_PAGE = 'DETAIL_OXIMETER_PAGE'

export const OMRON_PAGE = 'OMRON_PAGE'
